### ISSUE TITLE
update .dockerfunc: Chrome's function

### ISSUE THREAD

**Issue by JarenGlover** [jfrazelle/dotfiles#1]
The ```"--user-data-dir=/data"``` flag might be a duplicate, since a similar flag was provided in the ```CMD``` command in the respective Dockerfile (line 40). 

excerpt from the Dockerfile
```
# Autorun chrome
ENTRYPOINT [ "/usr/bin/google-chrome" ]
CMD [ "--user-data-dir=/data", "--no-sandbox" ]
```
=======
```
chrome(){
	del_stopped chrome

	docker run -d \
		--memory 5gb \
		--net host \
		-v /etc/localtime:/etc/localtime:ro \
		-v /tmp/.X11-unix:/tmp/.X11-unix \
		-e DISPLAY=unix$DISPLAY \
		-v $HOME/Downloads:/root/Downloads \
		-v $HOME/Pictures:/root/Pictures \
		-v $HOME/Torrents:/root/Torrents \
		-v $HOME/.chrome:/data \
		--device /dev/snd \
		--device /dev/dri \
		--device /dev/video0 \
		--name chrome \
		jess/chrome --user-data-dir=/data --force-device-scale-factor=1 "$@"

	# exit current shell
	exit 0
}
```

Side Note Question: Did you add the HiDPI support flag (```--force-device-scale-factor=1```) because this is something unique to your env (i.e. your monitor) or because at the time it was required to run the container? The matching pull request will only be an update for the data dir ... but wanted to ask because it crashes my container.

**Comment by jfrazelle** [comment]
No sorry these are my dotfiles and I use this function everyday feel free to fork

**Comment by jfrazelle** [comment]
The scale factor is because of hidpi is a personal preference and since I am overriding the cmd the data dir is not duplicated. It is how the cmd directive works in a dockerfile

**Comment by jfrazelle** [comment]
I purposely run _with_ the sandbox because I want OpenGL and crap to work right, watch my YouTube video from container camp and you will understand

**Comment by JarenGlover** [comment]
nice, i see ...mucho learnings here - thanks! your personal files are dope! Will take advice and keep any nuances in my fork. thx

**Comment by JarenGlover** [comment]
hi @jfrazelle --- I am wondering why you are not passing ```--no-sandbox``` in your dockerfunc for chrome? i.e. adding that arg to the override too?  -- adding that solves my problem - otherwise the other two args are not passed to the container (based on the docker inspect info --bug?) -- suspect maybe I am missing some context ...thanks

**Comment by jfrazelle** [comment]
It works better on my machine this way because I have the Graphics lobs in the container I purposely override the --no-sandbox so the default image works for people out of the box

**Comment by jfrazelle** [comment]
If you watch my talk from container camp I explain all of this
